/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Briefs = {
  project_code: string;
  brief: string;
  model: string;
  seed: number;
  generated_at: string;
  grounded: boolean;
  attempts: number;
  facts_hash: string;
}[];
