/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Sources = Source[];

export interface Findings {
  meta: {
    contract_version: string;
    generated_at: string;
    snapshots: string[];
    coverage: {
      snapshot: string;
      rows_parsed: number;
      rows_printed: number | null;
      pct: number | null;
    }[];
    headline: {
      projects_latest: number;
      cost_revised_total_cr: number;
      overrun_total_cr: number;
      contradictions_total: number;
      contradictions_arithmetic: number;
      statistical_anomalies: number;
      exits_total: number;
      unreachable_total: number;
      watchlist_size: number;
    };
    denominators: {
      cost_revised_null: number;
      cost_overrun_null: number;
      doc_null: number;
    };
  };
  contradictions: {
    by_type: {
      type: string;
      count: number;
    }[];
    rows: {
      project_code: string;
      project_name: string;
      type: string;
      severity: string;
      from_snapshot: string | null;
      to_snapshot: string;
      before: number | string | null;
      after: number | string | null;
      detail: string;
      sources: Sources;
    }[];
  };
  exits: {
    pairs: {
      from: string;
      to: string;
      exited: number;
      entered: number;
      exited_cost_revised_cr: number;
      commissioned_printed: number | null;
    }[];
    rows: {
      project_code: string;
      project_name: string;
      last_seen: string;
      last_progress_pct: number | null;
      last_expenditure_cr: number | null;
      last_cost_revised_cr: number | null;
      partition: "LAST_SEEN_GE_95" | "LAST_SEEN_50_95" | "LAST_SEEN_LT_50" | "UNKNOWN";
      sources: Sources;
    }[];
  };
  early_warning: {
    rows: {
      project_code: string;
      project_name: string;
      velocity_pct_per_month: number | null;
      months_needed: number | null;
      months_remaining: number;
      ratio: number | null;
      severity: string;
      sources: Sources;
    }[];
  };
  field_audit: {
    snapshot: string;
    terminal_digit: {
      digit: number;
      count: number;
      share: number;
    }[];
    whole_number_share: number;
    multiple_of_5_share: number;
    multiple_of_10_share: number;
    whipple_index: number | null;
    whipple_band: string | null;
    staleness_by_agency: {
      agency_raw: string;
      projects: number;
      share_unchanged: number;
    }[];
  };
  delay_series: {
    bands: string[];
    rows: {
      snapshot: string;
      on_schedule: number;
      d_1_12: number;
      d_13_24: number;
      d_25_60: number;
      d_61_plus: number;
      classifiable: number;
      doc_null: number;
    }[];
  };
  escalation: {
    threshold_pct: number;
    min_classifiable: number;
    rows: {
      key: string;
      projects: number;
      classifiable: number;
      delayed: number;
      delay_rate_pct: number | null;
      first_rate_pct: number | null;
      improving: boolean | null;
      escalate: boolean;
    }[];
  };
  disclosure_lag: {
    status: "computed" | "not_computed";
    median_lag_months: number | null;
    rows: {
      project_code: string;
      filed_at: string;
      first_unreachable: string | null;
      lag_months: number | null;
    }[];
  };
  by_state: Group[];
  by_sector: Group[];
  review_pack: {
    project_code: string;
    project_name: string;
    state: string | null;
    sector: string | null;
    risk_band: string;
    risk_score: number;
    slip_prob: number | null;
    expected_delay_months: number | null;
    flag_types: string;
    page: number;
  }[];
  assistant: {
    id: number;
    question: string;
    answer: string;
    sources: Sources;
  }[];
}
export interface Source {
  snapshot: string;
  page: number;
}
export interface Group {
  key: string;
  projects: number;
  flagged: number;
  red: number;
}
