/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Models {
  meta: {
    contract_version: string;
    generated_at: string;
    sklearn_version: string;
    random_state: number;
    omp_threads: number;
    pairs: {
      id: string;
      from: string;
      to: string;
      gap_months: number;
      n: number;
      positives: number;
      censored_exits: number;
    }[];
    test_pair: string;
    train_pairs: string[];
  };
  m1_slip: {
    feature_sets: {
      A: string[];
      B: string[];
    };
    results: {
      model_id: string;
      test_pair: string;
      n: number;
      positives: number;
      base_rate: number;
      pr_auc: number;
      roc_auc: number | null;
      precision_at_100: number;
      recall_at_100: number;
      lift_at_100: number | null;
      calibration: {
        bin: number;
        mean_pred: number | null;
        mean_obs: number | null;
        n: number;
      }[];
      pr_curve: Point[];
    }[];
    importance_HGB_B: {
      feature: string;
      mean: number;
      std: number;
    }[];
    coefficients_LR_A: Named[];
    watchlist: {
      project_code: string;
      slip_prob: number;
      slip_rank: number;
    }[];
  };
  m2_progress: {
    results: {
      model_id: string;
      test_pair: string;
      n: number;
      mae: number;
      median_ae: number;
    }[];
    winner: string;
    agreement_with_F3: {
      n: number;
      share_same_direction: number | null;
    };
  };
  m3_drivers: {
    snapshot: string;
    n: number;
    results: {
      target: string;
      model_id: string;
      cv_r2: number;
      cv_mae: number;
    }[];
    partial_dependence: {
      target: string;
      feature: string;
      grid: number[];
      values: number[];
    }[];
    sector_effects: {
      sector: string;
      effect_cost_pct: number;
      effect_time_months: number;
      n: number;
    }[];
    coefficients_OLS: {
      target: string;
      feature: string;
      coef: number;
    }[];
  };
  m4_anomaly: {
    n: number;
    contamination: string;
    flagged: {
      project_code: string;
      pair: string;
      score: number;
      sources: {
        snapshot: string;
        page: number;
      }[];
    }[];
  };
}
export interface Point {
  x: number;
  y: number;
}
export interface Named {
  feature: string;
  value: number;
}
