/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Projects = Project[];

export interface Project {
  project_code: string;
  project_name: string;
  agency_raw: string | null;
  state: string | null;
  sector: string | null;
  status: "ongoing" | "exited";
  first_seen: string;
  last_seen: string;
  /**
   * @minItems 1
   */
  snapshots: [SnapshotRow, ...SnapshotRow[]];
  flags: Flag[];
  risk: Risk;
  ml: null | ML;
}
export interface SnapshotRow {
  snapshot: string;
  page: number;
  doc_original: string | null;
  doc_revised: string | null;
  cost_original_cr: number | null;
  cost_revised_cr: number | null;
  expenditure_cum_cr: number | null;
  physical_progress_pct: number | null;
}
export interface Flag {
  type:
    | "EXP_DECREASE"
    | "PROG_DECREASE"
    | "EXP_GT_REVISED_COST"
    | "ZERO_PROG_NONZERO_EXP"
    | "PROG_GT_100"
    | "DOC_BEFORE_APPROVAL"
    | "DOC_PASSED"
    | "DOC_UNREACHABLE"
    | "DOC_REVISED_FILED"
    | "COST_REVISED_FILED"
    | "STAT_ANOMALY";
  severity: "critical" | "high" | "medium" | "low" | "info";
  from_snapshot: string | null;
  to_snapshot: string;
  before: number | string | null;
  after: number | string | null;
  detail: string;
  sources: Source[];
  first_snapshot?: string | null;
  occurrences?: number;
}
export interface Source {
  snapshot: string;
  page: number;
}
export interface Risk {
  score: number;
  band: "red" | "amber" | "green";
  reasons: string[];
}
export interface ML {
  slip_prob: number | null;
  slip_rank: number | null;
  slip_top_factors: Factor[];
  progress_next_pred: number | null;
  expected_completion: string | null;
  expected_delay_months: number | null;
  peer_expected_cost_overrun_pct: number | null;
  cost_overrun_residual_pct: number | null;
  peer_expected_time_overrun_months: number | null;
  time_overrun_residual_months: number | null;
  anomaly_score: number | null;
  anomaly_flag: boolean;
  scored_at_snapshot: string;
}
export interface Factor {
  feature: string;
  contribution: number;
  value: number | string | null;
}
